server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/jblog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
     show-sql: true
     hibernate.ddl-auto: update
  freemarker:
    template-loader-path: classpath:/web/
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
my-data:
  #blog名称
  blog-name: 海眼看世界
  #blog作者
  blog-author: H!Guo
  #twitter账号
  blog-twitter: freeguo
  #blog二维码
  blog-qrcode: https://guohai.org/assets/wechat.jpg